"""Обновление БД, добавление дополнительных строк\таблиц для HomePage

Revision ID: 119e8f1b988d
Revises: edbcea9fce48
Create Date: 2025-01-11 17:18:15.494695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119e8f1b988d'
down_revision: Union[str, None] = 'edbcea9fce48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
