"""Обновление БД, добавление таблицы наблюдателей

Revision ID: 40b3a2f82b29
Revises: 
Create Date: 2024-12-30 20:20:32.891328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b3a2f82b29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('issue_type', sa.Enum('task', 'bug', 'epic', name='issuetypeenum'), nullable=False))
    op.add_column('tasks', sa.Column('labels', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('flagged', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('team', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('only_for_roles', sa.String(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='taskstatus'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='taskpriority'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='taskpriority'),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('new', 'in_progress', 'completed', name='taskstatus'),
               nullable=True)
    op.drop_column('tasks', 'only_for_roles')
    op.drop_column('tasks', 'team')
    op.drop_column('tasks', 'flagged')
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'issue_type')
    # ### end Alembic commands ###
