"""Обновление БД

Revision ID: 6dbb64d7b97b
Revises: 80a147911890
Create Date: 2025-01-12 18:41:09.101053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dbb64d7b97b'
down_revision: Union[str, None] = '80a147911890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recent_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('teams', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'project_id')
    op.alter_column('recent_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
