"""Обновление БД

Revision ID: 8ee5f3d43330
Revises: 6dbb64d7b97b
Create Date: 2025-01-12 18:51:03.020725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee5f3d43330'
down_revision: Union[str, None] = '6dbb64d7b97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
