"""Обновление БД, добавление дополнительных строк

Revision ID: edbcea9fce48
Revises: 40b3a2f82b29
Create Date: 2025-01-11 16:54:58.400416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbcea9fce48'
down_revision: Union[str, None] = '40b3a2f82b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('last_updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['last_updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'last_updated_by_id')
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
